[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "trkbs-api"
dynamic = ["version"]
description = 'Tools for accessing Transkribus PAGE XML and working with semantic tags.'
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
keywords = []
authors = [
  { name = "Lev Shadrin", email = "lev.shadrin@uibk.ac.at" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "requests",
    "beautifulsoup4",
    "lxml",
    "pandas",
    "tqdm>=4.60",   # tqdm.contrib.logging (logging_redirect_tqdm)
    "python-dotenv",
    ]

[project.urls]
Homepage = "https://github.com/levshadrin/trkbs-api"
Repository = "https://github.com/levshadrin/trkbs-api"
Issues = "https://github.com/levshadrin/trkbs-api/issues"

[tool.hatch.build.targets.wheel]
packages = ["src/trkbs_api"]

[tool.hatch.version]
path = "src/trkbs_api/__about__.py"

[tool.hatch.envs.test]
extra-dependencies = [
  "pytest",
]
[tool.hatch.envs.test.scripts]
run = "pytest {args:tests}"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
  "pytest",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/trkbs_api tests}"

[tool.coverage.run]
source_pkgs = ["trkbs_api", "tests"]
branch = true
parallel = true
omit = [
  "src/trkbs_api/__about__.py",
]

[tool.coverage.paths]
trkbs_api = ["src/trkbs_api", "*/trkbs-api/src/trkbs_api"]
tests = ["tests", "*/trkbs-api/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
